//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soapClientM.soapM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sv/", ConfigurationName="soapM.servicios")]
    public interface servicios {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/par_imparRequest", ReplyAction="http://sv/servicios/par_imparResponse")]
        soapClientM.soapM.par_imparResponse par_impar(soapClientM.soapM.par_imparRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/par_imparRequest", ReplyAction="http://sv/servicios/par_imparResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.par_imparResponse> par_imparAsync(soapClientM.soapM.par_imparRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/valorResultadoRequest", ReplyAction="http://sv/servicios/valorResultadoResponse")]
        soapClientM.soapM.valorResultadoResponse valorResultado(soapClientM.soapM.valorResultadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/valorResultadoRequest", ReplyAction="http://sv/servicios/valorResultadoResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.valorResultadoResponse> valorResultadoAsync(soapClientM.soapM.valorResultadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/helloRequest", ReplyAction="http://sv/servicios/helloResponse")]
        soapClientM.soapM.helloResponse hello(soapClientM.soapM.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/helloRequest", ReplyAction="http://sv/servicios/helloResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.helloResponse> helloAsync(soapClientM.soapM.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://sv/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/potenciaRequest", ReplyAction="http://sv/servicios/potenciaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientM.soapM.potenciaResponse potencia(soapClientM.soapM.potenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/potenciaRequest", ReplyAction="http://sv/servicios/potenciaResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.potenciaResponse> potenciaAsync(soapClientM.soapM.potenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento palabra del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/diccionarioRequest", ReplyAction="http://sv/servicios/diccionarioResponse")]
        soapClientM.soapM.diccionarioResponse diccionario(soapClientM.soapM.diccionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/diccionarioRequest", ReplyAction="http://sv/servicios/diccionarioResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.diccionarioResponse> diccionarioAsync(soapClientM.soapM.diccionarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://sv/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/sumaRequest", ReplyAction="http://sv/servicios/sumaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientM.soapM.sumaResponse suma(soapClientM.soapM.sumaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/sumaRequest", ReplyAction="http://sv/servicios/sumaResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.sumaResponse> sumaAsync(soapClientM.soapM.sumaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://sv/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/restaRequest", ReplyAction="http://sv/servicios/restaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientM.soapM.restaResponse resta(soapClientM.soapM.restaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/restaRequest", ReplyAction="http://sv/servicios/restaResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.restaResponse> restaAsync(soapClientM.soapM.restaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://sv/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/multiplicacionRequest", ReplyAction="http://sv/servicios/multiplicacionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        soapClientM.soapM.multiplicacionResponse multiplicacion(soapClientM.soapM.multiplicacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/multiplicacionRequest", ReplyAction="http://sv/servicios/multiplicacionResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.multiplicacionResponse> multiplicacionAsync(soapClientM.soapM.multiplicacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/loginRequest", ReplyAction="http://sv/servicios/loginResponse")]
        soapClientM.soapM.loginResponse login(soapClientM.soapM.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/servicios/loginRequest", ReplyAction="http://sv/servicios/loginResponse")]
        System.Threading.Tasks.Task<soapClientM.soapM.loginResponse> loginAsync(soapClientM.soapM.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class par_imparRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="par_impar", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.par_imparRequestBody Body;
        
        public par_imparRequest() {
        }
        
        public par_imparRequest(soapClientM.soapM.par_imparRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class par_imparRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numero;
        
        public par_imparRequestBody() {
        }
        
        public par_imparRequestBody(int numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class par_imparResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="par_imparResponse", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.par_imparResponseBody Body;
        
        public par_imparResponse() {
        }
        
        public par_imparResponse(soapClientM.soapM.par_imparResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class par_imparResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public par_imparResponseBody() {
        }
        
        public par_imparResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class valorResultadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="valorResultado", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.valorResultadoRequestBody Body;
        
        public valorResultadoRequest() {
        }
        
        public valorResultadoRequest(soapClientM.soapM.valorResultadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class valorResultadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public valorResultadoRequestBody() {
        }
        
        public valorResultadoRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class valorResultadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="valorResultadoResponse", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.valorResultadoResponseBody Body;
        
        public valorResultadoResponse() {
        }
        
        public valorResultadoResponse(soapClientM.soapM.valorResultadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class valorResultadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public valorResultadoResponseBody() {
        }
        
        public valorResultadoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(soapClientM.soapM.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(soapClientM.soapM.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="potencia", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class potenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @base;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double exponente;
        
        public potenciaRequest() {
        }
        
        public potenciaRequest(double @base, double exponente) {
            this.@base = @base;
            this.exponente = exponente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="potenciaResponse", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class potenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public potenciaResponse() {
        }
        
        public potenciaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class diccionarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="diccionario", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.diccionarioRequestBody Body;
        
        public diccionarioRequest() {
        }
        
        public diccionarioRequest(soapClientM.soapM.diccionarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class diccionarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string palabra;
        
        public diccionarioRequestBody() {
        }
        
        public diccionarioRequestBody(string palabra) {
            this.palabra = palabra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class diccionarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="diccionarioResponse", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.diccionarioResponseBody Body;
        
        public diccionarioResponse() {
        }
        
        public diccionarioResponse(soapClientM.soapM.diccionarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class diccionarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public diccionarioResponseBody() {
        }
        
        public diccionarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="suma", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class sumaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double Num2;
        
        public sumaRequest() {
        }
        
        public sumaRequest(double Num1, double Num2) {
            this.Num1 = Num1;
            this.Num2 = Num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumaResponse", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class sumaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sumaResponse() {
        }
        
        public sumaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resta", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class restaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double Num2;
        
        public restaRequest() {
        }
        
        public restaRequest(double Num1, double Num2) {
            this.Num1 = Num1;
            this.Num2 = Num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restaResponse", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class restaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public restaResponse() {
        }
        
        public restaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacion", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class multiplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double Num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double Num2;
        
        public multiplicacionRequest() {
        }
        
        public multiplicacionRequest(double Num1, double Num2) {
            this.Num1 = Num1;
            this.Num2 = Num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicacionResponse", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class multiplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplicacionResponse() {
        }
        
        public multiplicacionResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(soapClientM.soapM.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://sv/", Order=0)]
        public soapClientM.soapM.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(soapClientM.soapM.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosChannel : soapClientM.soapM.servicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosClient : System.ServiceModel.ClientBase<soapClientM.soapM.servicios>, soapClientM.soapM.servicios {
        
        public serviciosClient() {
        }
        
        public serviciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.par_imparResponse soapClientM.soapM.servicios.par_impar(soapClientM.soapM.par_imparRequest request) {
            return base.Channel.par_impar(request);
        }
        
        public string par_impar(int numero) {
            soapClientM.soapM.par_imparRequest inValue = new soapClientM.soapM.par_imparRequest();
            inValue.Body = new soapClientM.soapM.par_imparRequestBody();
            inValue.Body.numero = numero;
            soapClientM.soapM.par_imparResponse retVal = ((soapClientM.soapM.servicios)(this)).par_impar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.par_imparResponse> soapClientM.soapM.servicios.par_imparAsync(soapClientM.soapM.par_imparRequest request) {
            return base.Channel.par_imparAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.par_imparResponse> par_imparAsync(int numero) {
            soapClientM.soapM.par_imparRequest inValue = new soapClientM.soapM.par_imparRequest();
            inValue.Body = new soapClientM.soapM.par_imparRequestBody();
            inValue.Body.numero = numero;
            return ((soapClientM.soapM.servicios)(this)).par_imparAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.valorResultadoResponse soapClientM.soapM.servicios.valorResultado(soapClientM.soapM.valorResultadoRequest request) {
            return base.Channel.valorResultado(request);
        }
        
        public string valorResultado(string arg0) {
            soapClientM.soapM.valorResultadoRequest inValue = new soapClientM.soapM.valorResultadoRequest();
            inValue.Body = new soapClientM.soapM.valorResultadoRequestBody();
            inValue.Body.arg0 = arg0;
            soapClientM.soapM.valorResultadoResponse retVal = ((soapClientM.soapM.servicios)(this)).valorResultado(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.valorResultadoResponse> soapClientM.soapM.servicios.valorResultadoAsync(soapClientM.soapM.valorResultadoRequest request) {
            return base.Channel.valorResultadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.valorResultadoResponse> valorResultadoAsync(string arg0) {
            soapClientM.soapM.valorResultadoRequest inValue = new soapClientM.soapM.valorResultadoRequest();
            inValue.Body = new soapClientM.soapM.valorResultadoRequestBody();
            inValue.Body.arg0 = arg0;
            return ((soapClientM.soapM.servicios)(this)).valorResultadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.helloResponse soapClientM.soapM.servicios.hello(soapClientM.soapM.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            soapClientM.soapM.helloRequest inValue = new soapClientM.soapM.helloRequest();
            inValue.Body = new soapClientM.soapM.helloRequestBody();
            inValue.Body.name = name;
            soapClientM.soapM.helloResponse retVal = ((soapClientM.soapM.servicios)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.helloResponse> soapClientM.soapM.servicios.helloAsync(soapClientM.soapM.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.helloResponse> helloAsync(string name) {
            soapClientM.soapM.helloRequest inValue = new soapClientM.soapM.helloRequest();
            inValue.Body = new soapClientM.soapM.helloRequestBody();
            inValue.Body.name = name;
            return ((soapClientM.soapM.servicios)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.potenciaResponse soapClientM.soapM.servicios.potencia(soapClientM.soapM.potenciaRequest request) {
            return base.Channel.potencia(request);
        }
        
        public double potencia(double @base, double exponente) {
            soapClientM.soapM.potenciaRequest inValue = new soapClientM.soapM.potenciaRequest();
            inValue.@base = @base;
            inValue.exponente = exponente;
            soapClientM.soapM.potenciaResponse retVal = ((soapClientM.soapM.servicios)(this)).potencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.potenciaResponse> soapClientM.soapM.servicios.potenciaAsync(soapClientM.soapM.potenciaRequest request) {
            return base.Channel.potenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.potenciaResponse> potenciaAsync(double @base, double exponente) {
            soapClientM.soapM.potenciaRequest inValue = new soapClientM.soapM.potenciaRequest();
            inValue.@base = @base;
            inValue.exponente = exponente;
            return ((soapClientM.soapM.servicios)(this)).potenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.diccionarioResponse soapClientM.soapM.servicios.diccionario(soapClientM.soapM.diccionarioRequest request) {
            return base.Channel.diccionario(request);
        }
        
        public string diccionario(string palabra) {
            soapClientM.soapM.diccionarioRequest inValue = new soapClientM.soapM.diccionarioRequest();
            inValue.Body = new soapClientM.soapM.diccionarioRequestBody();
            inValue.Body.palabra = palabra;
            soapClientM.soapM.diccionarioResponse retVal = ((soapClientM.soapM.servicios)(this)).diccionario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.diccionarioResponse> soapClientM.soapM.servicios.diccionarioAsync(soapClientM.soapM.diccionarioRequest request) {
            return base.Channel.diccionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.diccionarioResponse> diccionarioAsync(string palabra) {
            soapClientM.soapM.diccionarioRequest inValue = new soapClientM.soapM.diccionarioRequest();
            inValue.Body = new soapClientM.soapM.diccionarioRequestBody();
            inValue.Body.palabra = palabra;
            return ((soapClientM.soapM.servicios)(this)).diccionarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.sumaResponse soapClientM.soapM.servicios.suma(soapClientM.soapM.sumaRequest request) {
            return base.Channel.suma(request);
        }
        
        public double suma(double Num1, double Num2) {
            soapClientM.soapM.sumaRequest inValue = new soapClientM.soapM.sumaRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            soapClientM.soapM.sumaResponse retVal = ((soapClientM.soapM.servicios)(this)).suma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.sumaResponse> soapClientM.soapM.servicios.sumaAsync(soapClientM.soapM.sumaRequest request) {
            return base.Channel.sumaAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.sumaResponse> sumaAsync(double Num1, double Num2) {
            soapClientM.soapM.sumaRequest inValue = new soapClientM.soapM.sumaRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            return ((soapClientM.soapM.servicios)(this)).sumaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.restaResponse soapClientM.soapM.servicios.resta(soapClientM.soapM.restaRequest request) {
            return base.Channel.resta(request);
        }
        
        public double resta(double Num1, double Num2) {
            soapClientM.soapM.restaRequest inValue = new soapClientM.soapM.restaRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            soapClientM.soapM.restaResponse retVal = ((soapClientM.soapM.servicios)(this)).resta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.restaResponse> soapClientM.soapM.servicios.restaAsync(soapClientM.soapM.restaRequest request) {
            return base.Channel.restaAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.restaResponse> restaAsync(double Num1, double Num2) {
            soapClientM.soapM.restaRequest inValue = new soapClientM.soapM.restaRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            return ((soapClientM.soapM.servicios)(this)).restaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.multiplicacionResponse soapClientM.soapM.servicios.multiplicacion(soapClientM.soapM.multiplicacionRequest request) {
            return base.Channel.multiplicacion(request);
        }
        
        public double multiplicacion(double Num1, double Num2) {
            soapClientM.soapM.multiplicacionRequest inValue = new soapClientM.soapM.multiplicacionRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            soapClientM.soapM.multiplicacionResponse retVal = ((soapClientM.soapM.servicios)(this)).multiplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.multiplicacionResponse> soapClientM.soapM.servicios.multiplicacionAsync(soapClientM.soapM.multiplicacionRequest request) {
            return base.Channel.multiplicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.multiplicacionResponse> multiplicacionAsync(double Num1, double Num2) {
            soapClientM.soapM.multiplicacionRequest inValue = new soapClientM.soapM.multiplicacionRequest();
            inValue.Num1 = Num1;
            inValue.Num2 = Num2;
            return ((soapClientM.soapM.servicios)(this)).multiplicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soapClientM.soapM.loginResponse soapClientM.soapM.servicios.login(soapClientM.soapM.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string user, string password) {
            soapClientM.soapM.loginRequest inValue = new soapClientM.soapM.loginRequest();
            inValue.Body = new soapClientM.soapM.loginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            soapClientM.soapM.loginResponse retVal = ((soapClientM.soapM.servicios)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soapClientM.soapM.loginResponse> soapClientM.soapM.servicios.loginAsync(soapClientM.soapM.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<soapClientM.soapM.loginResponse> loginAsync(string user, string password) {
            soapClientM.soapM.loginRequest inValue = new soapClientM.soapM.loginRequest();
            inValue.Body = new soapClientM.soapM.loginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((soapClientM.soapM.servicios)(this)).loginAsync(inValue);
        }
    }
}
